name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  # 允許您從 Actions 標籤手動執行此工作流程
  workflow_dispatch:

# 設定 GITHUB_TOKEN 的權限，以允許部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允許一個並發部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # 如果使用主題作為子模組，則獲取它們
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
          
      - name: Build with Hugo
        run: hugo --minify --cleanDestinationDir # 將網站建置到 'public' 目錄中
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' # 僅在推送到 main 分支時部署
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # 要發佈的目錄
          # 'publish_branch' 輸入預設為 'gh-pages'

